name: pandoc-confluence
version: 0.1.0.0
synopsis: Pandoc writer for Confluence's XHTML-based format.
category: Text
github: "farbodsz/pandoc-confluence"
license: MIT
description: Please see the README on GitHub at <https://github.com/farbodsz/pandoc-confluence#readme>
author: "Farbod Salamat-Zadeh"
copyright: "2022 Farbod Salamat-Zadeh"
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - pandoc-types
  - text

default-extensions:
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  pandoc-confluence:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pandoc-confluence
